name: Test Vault Action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          vault-url: ${{ vars.VAULT_ADDR }}
          vault-token: ${{ secrets.VAULT_TOKEN }}
          vault-secret-path: 'secret/data/data/test'
          template-file: 'templates/config.tpl'
          output-file: 'output/config.ini'

      - name: Test Action (Credentials)
        uses: ./
        with:
          vault-url: ${{ vars.VAULT_ADDR }}
          vault-token: ${{ secrets.VAULT_TOKEN }}
          vault-secret-path: 'secret/data/data/test'
          template-file: 'templates/credentials.tpl'
          output-file: 'output/credentials.ini'
